// Mocks generated by Mockito 5.4.4 from annotations
// in frontend/test/user_preferences_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:frontend/data/enums.dart' as _i3;
import 'package:frontend/local/user_preferences.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserPreferences extends _i1.Mock implements _i2.UserPreferences {
  MockUserPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void saveLoginInfo(
    int? userId,
    String? username,
    String? dateOfBirth,
    _i3.Gender? gender,
    String? token,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #saveLoginInfo,
          [
            userId,
            username,
            dateOfBirth,
            gender,
            token,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<Map<String, dynamic>?> getLoginInfo() => (super.noSuchMethod(
        Invocation.method(
          #getLoginInfo,
          [],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<_i5.SharedPreferences?> deleteLoginInfo() => (super.noSuchMethod(
        Invocation.method(
          #deleteLoginInfo,
          [],
        ),
        returnValue: _i4.Future<_i5.SharedPreferences?>.value(),
      ) as _i4.Future<_i5.SharedPreferences?>);
}
