# Generated by Django 4.2.16 on 2024-12-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaccination_tracking_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("PATIENT", "Patient"),
                    ("DOCTOR", "Doctor"),
                    ("ADMIN", "Admin"),
                ],
                default="ADMIN",
                max_length=10,
            ),
        ),
    ]
