# Generated by Django 4.2.16 on 2024-12-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaccination_tracking_app", "0003_alter_customuser_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="Male",
                max_length=10,
            ),
        ),
    ]
