# Generated by Django 4.2.16 on 2024-12-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaccination_tracking_app", "0005_availabletimeslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="availabletimeslot",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
